"""empty message

Revision ID: 12bd6d69e03f
Revises: 1f457020df4a
Create Date: 2020-11-08 10:42:01.585911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12bd6d69e03f'
down_revision = '1f457020df4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('office', sa.String(length=20), nullable=False))
    op.drop_column('teacher', 'office_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('office_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('teacher', 'office')
    # ### end Alembic commands ###
