"""empty message

Revision ID: 1f457020df4a
Revises: 2608c6f059be
Create Date: 2020-11-01 17:16:32.241287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f457020df4a'
down_revision = '2608c6f059be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('term', sa.String(length=10), nullable=False))
    op.drop_column('elective', 'term')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective', sa.Column('term', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('course', 'term')
    # ### end Alembic commands ###
