"""empty message

Revision ID: 2608c6f059be
Revises: 5c8cf9c4fc70
Create Date: 2020-11-01 17:13:17.547941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2608c6f059be'
down_revision = '5c8cf9c4fc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'term')
    op.add_column('elective', sa.Column('term', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elective', 'term')
    op.add_column('course', sa.Column('term', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
