"""empty message

Revision ID: 4f20b69d734e
Revises: 61cfca922c6c
Create Date: 2020-11-19 21:50:52.870431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f20b69d734e'
down_revision = '61cfca922c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('pwd', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login')
    # ### end Alembic commands ###
