"""empty message

Revision ID: 5031a6d736ad
Revises: 5539c6a8df91
Create Date: 2020-11-20 16:19:13.949658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5031a6d736ad'
down_revision = '5539c6a8df91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('class_ibfk_1', 'class', type_='foreignkey')
    op.create_foreign_key(None, 'class', 'major', ['mid'], ['mid'], ondelete='CASCADE')
    op.drop_constraint('course_ibfk_2', 'course', type_='foreignkey')
    op.drop_constraint('course_ibfk_1', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'academy', ['aname'], ['aname'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course', 'teacher', ['tid'], ['tid'], ondelete='CASCADE')
    op.drop_constraint('major_ibfk_1', 'major', type_='foreignkey')
    op.create_foreign_key(None, 'major', 'academy', ['aname'], ['aname'], ondelete='CASCADE')
    op.drop_constraint('teacher_ibfk_1', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'academy', ['aname'], ['aname'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key('teacher_ibfk_1', 'teacher', 'academy', ['aname'], ['aname'])
    op.drop_constraint(None, 'major', type_='foreignkey')
    op.create_foreign_key('major_ibfk_1', 'major', 'academy', ['aname'], ['aname'])
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_ibfk_1', 'course', 'teacher', ['tid'], ['tid'])
    op.create_foreign_key('course_ibfk_2', 'course', 'academy', ['aname'], ['aname'])
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.create_foreign_key('class_ibfk_1', 'class', 'major', ['mid'], ['mid'])
    # ### end Alembic commands ###
