"""empty message

Revision ID: 5539c6a8df91
Revises: a637d918da8f
Create Date: 2020-11-20 16:12:51.350663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5539c6a8df91'
down_revision = 'a637d918da8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'class', ['cid'], ['cid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'class', ['cid'], ['cid'])
    # ### end Alembic commands ###
