"""empty message

Revision ID: 5c8cf9c4fc70
Revises: c7512ec4b61b
Create Date: 2020-11-01 11:48:40.279704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8cf9c4fc70'
down_revision = 'c7512ec4b61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective', sa.Column('eid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elective', 'eid')
    # ### end Alembic commands ###
