"""empty message

Revision ID: 61cfca922c6c
Revises: 75e9f82523d3
Create Date: 2020-11-13 18:26:03.254796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cfca922c6c'
down_revision = '75e9f82523d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy', sa.Column('aid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academy', 'aid')
    # ### end Alembic commands ###
