"""empty message

Revision ID: 75e9f82523d3
Revises: af2736ec8af7
Create Date: 2020-11-08 11:57:22.467978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75e9f82523d3'
down_revision = 'af2736ec8af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'title',
               existing_type=mysql.ENUM('教授', '副教授', '讲师'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'title',
               existing_type=mysql.ENUM('教授', '副教授', '讲师'),
               nullable=True)
    # ### end Alembic commands ###
