"""empty message

Revision ID: 869fbcf21188
Revises: 
Create Date: 2020-10-31 17:01:20.847456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869fbcf21188'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('credit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'credit')
    # ### end Alembic commands ###
