"""empty message

Revision ID: a637d918da8f
Revises: 4f20b69d734e
Create Date: 2020-11-20 15:56:28.230103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a637d918da8f'
down_revision = '4f20b69d734e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('major_ibfk_1', 'major', type_='foreignkey')
    op.create_foreign_key(None, 'major', 'academy', ['aname'], ['aname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'major', type_='foreignkey')
    op.create_foreign_key('major_ibfk_1', 'major', 'academy', ['aname'], ['aname'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
