"""empty message

Revision ID: a78b6aac2e36
Revises: 869fbcf21188
Create Date: 2020-10-31 17:28:50.195223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78b6aac2e36'
down_revision = '869fbcf21188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elective',
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['course.cid'], ),
    sa.ForeignKeyConstraint(['sid'], ['student.sid'], )
    )
    op.add_column('class', sa.Column('mname', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'class', 'major', ['mname'], ['mname'])
    op.add_column('course', sa.Column('term', sa.String(length=10), nullable=False))
    op.add_column('course', sa.Column('tid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'teacher', ['tid'], ['tid'])
    op.add_column('student', sa.Column('cid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'class', ['cid'], ['cid'])
    op.add_column('teacher', sa.Column('aname', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'teacher', 'academy', ['aname'], ['aname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'aname')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'cid')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'tid')
    op.drop_column('course', 'term')
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'mname')
    op.drop_table('elective')
    # ### end Alembic commands ###
