"""empty message

Revision ID: c7512ec4b61b
Revises: a78b6aac2e36
Create Date: 2020-10-31 21:48:01.839520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7512ec4b61b'
down_revision = 'a78b6aac2e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('aname', sa.String(length=20), nullable=True))
    op.add_column('course', sa.Column('period', sa.String(length=3), nullable=True))
    op.create_foreign_key(None, 'course', 'academy', ['aname'], ['aname'])
    op.add_column('teacher', sa.Column('title', sa.Enum('教授', '副教授', '讲师'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'title')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'period')
    op.drop_column('course', 'aname')
    # ### end Alembic commands ###
