"""empty message

Revision ID: eb618633ad79
Revises: 5031a6d736ad
Create Date: 2020-11-21 15:11:22.625618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb618633ad79'
down_revision = '5031a6d736ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy', sa.Column('number', sa.Integer(), nullable=False))
    op.alter_column('academy', 'aid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='学院号',
               existing_nullable=False)
    op.alter_column('academy', 'aname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment=None,
               existing_comment='学院名')
    op.alter_column('class', 'cid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='班级号',
               autoincrement=True)
    op.alter_column('class', 'cname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10),
               comment=None,
               existing_comment='班级名',
               existing_nullable=False)
    op.alter_column('class', 'mid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='专业号',
               existing_nullable=True)
    op.alter_column('course', 'aname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment=None,
               existing_comment='学院名',
               existing_nullable=True)
    op.alter_column('course', 'cid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='课程号',
               autoincrement=True)
    op.alter_column('course', 'cname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10),
               comment=None,
               existing_comment='课程名',
               existing_nullable=False)
    op.alter_column('course', 'credit',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='学分',
               existing_nullable=False)
    op.alter_column('course', 'period',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=3),
               comment=None,
               existing_comment='学时',
               existing_nullable=True)
    op.alter_column('course', 'term',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10),
               comment=None,
               existing_comment='学期',
               existing_nullable=False)
    op.alter_column('course', 'tid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='教师号',
               existing_nullable=True)
    op.drop_index('term_index', table_name='course')
    op.alter_column('elective', 'cid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='课程号',
               existing_nullable=True)
    op.alter_column('elective', 'eid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='选修号',
               autoincrement=True)
    op.alter_column('elective', 'grade',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='成绩',
               existing_nullable=False)
    op.alter_column('elective', 'sid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='学号',
               existing_nullable=True)
    op.alter_column('login', 'pwd',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=16),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
    op.alter_column('login', 'username',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment=None,
               existing_comment='用户名')
    op.alter_column('major', 'aname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment=None,
               existing_comment='学院名',
               existing_nullable=True)
    op.alter_column('major', 'mid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='专业号',
               autoincrement=True)
    op.alter_column('major', 'mname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10),
               comment=None,
               existing_comment='专业名',
               existing_nullable=False)
    op.alter_column('student', 'cid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='班级号',
               existing_nullable=True)
    op.alter_column('student', 'gender',
               existing_type=mysql.ENUM('男', '女', charset='utf8', collation='utf8_general_ci'),
               comment=None,
               existing_comment='性别',
               existing_nullable=False)
    op.alter_column('student', 'sid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='学号',
               autoincrement=True)
    op.alter_column('student', 'sname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment=None,
               existing_comment='学生名',
               existing_nullable=False)
    op.alter_column('teacher', 'aname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment=None,
               existing_comment='学院名',
               existing_nullable=True)
    op.alter_column('teacher', 'gender',
               existing_type=mysql.ENUM('男', '女', charset='utf8', collation='utf8_general_ci'),
               comment=None,
               existing_comment='性别',
               existing_nullable=False)
    op.alter_column('teacher', 'office',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment=None,
               existing_comment='办公室',
               existing_nullable=True)
    op.alter_column('teacher', 'tid',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='教师号',
               autoincrement=True)
    op.alter_column('teacher', 'title',
               existing_type=mysql.ENUM('教授', '副教授', '讲师', charset='utf8', collation='utf8_general_ci'),
               comment=None,
               existing_comment='职称',
               existing_nullable=False)
    op.alter_column('teacher', 'tname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment=None,
               existing_comment='教师名',
               existing_nullable=False)
    op.drop_index('title_index', table_name='teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title_index', 'teacher', ['title'], unique=False)
    op.alter_column('teacher', 'tname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment='教师名',
               existing_nullable=False)
    op.alter_column('teacher', 'title',
               existing_type=mysql.ENUM('教授', '副教授', '讲师', charset='utf8', collation='utf8_general_ci'),
               comment='职称',
               existing_nullable=False)
    op.alter_column('teacher', 'tid',
               existing_type=mysql.INTEGER(),
               comment='教师号',
               autoincrement=True)
    op.alter_column('teacher', 'office',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment='办公室',
               existing_nullable=True)
    op.alter_column('teacher', 'gender',
               existing_type=mysql.ENUM('男', '女', charset='utf8', collation='utf8_general_ci'),
               comment='性别',
               existing_nullable=False)
    op.alter_column('teacher', 'aname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment='学院名',
               existing_nullable=True)
    op.alter_column('student', 'sname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment='学生名',
               existing_nullable=False)
    op.alter_column('student', 'sid',
               existing_type=mysql.INTEGER(),
               comment='学号',
               autoincrement=True)
    op.alter_column('student', 'gender',
               existing_type=mysql.ENUM('男', '女', charset='utf8', collation='utf8_general_ci'),
               comment='性别',
               existing_nullable=False)
    op.alter_column('student', 'cid',
               existing_type=mysql.INTEGER(),
               comment='班级号',
               existing_nullable=True)
    op.alter_column('major', 'mname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10),
               comment='专业名',
               existing_nullable=False)
    op.alter_column('major', 'mid',
               existing_type=mysql.INTEGER(),
               comment='专业号',
               autoincrement=True)
    op.alter_column('major', 'aname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment='学院名',
               existing_nullable=True)
    op.alter_column('login', 'username',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment='用户名')
    op.alter_column('login', 'pwd',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=16),
               comment='密码',
               existing_nullable=False)
    op.alter_column('elective', 'sid',
               existing_type=mysql.INTEGER(),
               comment='学号',
               existing_nullable=True)
    op.alter_column('elective', 'grade',
               existing_type=mysql.INTEGER(),
               comment='成绩',
               existing_nullable=False)
    op.alter_column('elective', 'eid',
               existing_type=mysql.INTEGER(),
               comment='选修号',
               autoincrement=True)
    op.alter_column('elective', 'cid',
               existing_type=mysql.INTEGER(),
               comment='课程号',
               existing_nullable=True)
    op.create_index('term_index', 'course', ['term'], unique=False)
    op.alter_column('course', 'tid',
               existing_type=mysql.INTEGER(),
               comment='教师号',
               existing_nullable=True)
    op.alter_column('course', 'term',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10),
               comment='学期',
               existing_nullable=False)
    op.alter_column('course', 'period',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=3),
               comment='学时',
               existing_nullable=True)
    op.alter_column('course', 'credit',
               existing_type=mysql.INTEGER(),
               comment='学分',
               existing_nullable=False)
    op.alter_column('course', 'cname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10),
               comment='课程名',
               existing_nullable=False)
    op.alter_column('course', 'cid',
               existing_type=mysql.INTEGER(),
               comment='课程号',
               autoincrement=True)
    op.alter_column('course', 'aname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment='学院名',
               existing_nullable=True)
    op.alter_column('class', 'mid',
               existing_type=mysql.INTEGER(),
               comment='专业号',
               existing_nullable=True)
    op.alter_column('class', 'cname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10),
               comment='班级名',
               existing_nullable=False)
    op.alter_column('class', 'cid',
               existing_type=mysql.INTEGER(),
               comment='班级号',
               autoincrement=True)
    op.alter_column('academy', 'aname',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20),
               comment='学院名')
    op.alter_column('academy', 'aid',
               existing_type=mysql.INTEGER(),
               comment='学院号',
               existing_nullable=False)
    op.drop_column('academy', 'number')
    # ### end Alembic commands ###
